# -*- coding: utf-8 -*-
"""Python 101.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VbS5JuGpJF_IY2B0cUAVaQACJcL5m3bg
"""



"""IPYNB = IPython Notebook"""

## Python 101



"""Data Structures in Python
1. String  str 
2. Integer  int
3. Float  float
"""

my_string = "Python"

print (my_string)

print ("my_string")

type (my_string)

my_int = 100

type(my_int)

my_int + 50

my_int / 2, my_int * 2

my_float = 3.14

type(my_float)

"""# Strings"""

my_string1 = "My favourit language is Python LOL"

len (my_string1)

my_string1.capitalize()

my_string1.upper()

my_string1.lower()

my_string1.title()

my_string1.count("a")

my_string1.count("y")

my_string1.count("lol")

my_string1.count("LOL")

my_string1.index("y")

my_string1.index("LOL")

my_string1.endswith("LOL")

my_string1.lower().count("lol")

my_string1.index("Python")

my_string1.startswith("My")

my_string1 * 5

my_string1 / 5

my_string1 + 5

my_string1 ** 5

my_string1 + "5"

my_string1 + str(5)

my_string1 + str( 5)

my_string1 + " " str(5)

my_string1 + " " + str(5)

my_string + my_string1

my_string + " " + my_string1

my_string + " :: " + my_string1

my_string1.split("y")

my_string1.split(" ")

my_string2 = "  Hello World of Python  "

len (my_string2)

my_string2.strip()

my_string2

my_string3 = my_string2.strip()

my_string3

my_string2.lstrip()

my_string2.rstrip()

a = "python"

a.upper()

a

a = a.upper()

a

a  = 10
b = a
b = b -2
a, b

"""### Slicing and Indexing *String*"""

my_string

len(my_string)

my_string[0]

my_string[4]

my_string[2]

my_string[-4]

my_string2

my_string1

my_string1[-4]

my_string[0:3]

my_string[2:5]

my_string[2:5:1]

"""Slicing - 
[start: stop: step]

1. start
2. start + step 
3. start + step + step 
4. start + step + step + step 

...
...
Until stop is reached.
"""

my_string[0:6:2]

my_string[0:4:2]

my_string2

my_string[0:4]

my_string[0:4:3]

my_string[0::2]

my_string[::2]

my_string[0:5:1]

my_string[::1]

my_string[-2:-6:-1]

"""```
-6   -5   -4  -3  -2  -1 
P     y    t   h   o   n 
0     1    2   3   4   5 
```
"""

my_string[-4:-1:1]

