# -*- coding: utf-8 -*-
"""Python102.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ywwr2jFH-zxhucdj2c5ms-5BCEpqAfTS
"""

! free -m

"""Intergers 

```
# This is formatted as code
```
"""

my_int = 100

id(my_int)

type(my_int)

str(my_int)

my_str = "200"

type(my_str)

int(my_str)

int("200e")

a =10
b=10
c=10
print(id(a))
print(id(b))
print(id(c))

b = b*5

print(id(a))
print(id(b))
print(id(c))

"""Float"""

my_float=3.14

type(my_float)

str(my_float)

int(my_float)

my_float=3.999999

int(my_float)

i = 10/5

10/5

import sys

sys.version

100_000

import datetime

my_time=datetime.datetime.now()

type(my_time)

str(my_time)

my_time.date()

"""New Data Type

List list []

Tuple tuple ()

Dictionary dict {}
"""

my_list = [212,23.23,'Test']

type(my_list)

len(my_list)

my_list[1]

my_list[2]

my_list[10]

my_list.append(44.23)

print(my_list)

my_list.pop()

my_list

my_list.insert(0,"First")

my_list

my_list.remove(212)

my_list

my_list.insert(3,3.14)

my_list

my_list.remove(3.14)

my_list

my_list.pop(2)

my_list.insert(1,3.14)
my_list.insert(3,3.14)

my_list

my_list.count(3.14)

[i for i in my_list if not i == 3.14]

my_list

my_list.sort()

my_list.reverse()

my_list

my_list[2:4]

my_list[3]

my_list[::-1]

my_list[::-2]

my_list[3:-2]

my_list[3:-2-1]

my_list

my_list[::2]

my_list[::-2]

